version: "3.8"

services:
  app:
    build: .
    container_name: the_brazilian_stars_v2
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - DATABASE_URL=file:/app/data/database.db
      - JWT_SECRET=sua_chave_secreta_brazilian_stars_2025
    volumes:
      # Volume nomeado para persistir dados do SQLite
      - brazilian_stars_data:/app/data

volumes:
  brazilian_stars_data:
    driver: local